### ISSUE TITLE
Errors happen when testing constructor in a Java class

### ISSUE THREAD

**Issue by yangyixiaof** [psycopaths/jdart#12]
In the directory jdart/src/examples/features/simple, if run test_ctor.jpf, errors happen. The rest of files are of no problems. The test_ctor.jpf file is about to test the constructor of a class.
Here is the error:
Exception in thread "main" ---------------------- JPF error stack trace ---------------------
JPF configuration error: error instantiating class gov.nasa.jpf.jdart.JDart for entry "shell":
> exception in gov.nasa.jpf.jdart.JDart(gov.nasa.jpf.Config):
>> java.lang.NullPointerException
	at gov.nasa.jpf.Config.getInstance(Config.java:2015)
	at gov.nasa.jpf.Config.getInstance(Config.java:1889)
	at gov.nasa.jpf.Config.getInstance(Config.java:1880)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:106)
Caused by: java.lang.NullPointerException
	at gov.nasa.jpf.jdart.config.MethodSpec.parse(MethodSpec.java:33)
	at gov.nasa.jpf.jdart.config.MethodSpec.parse(MethodSpec.java:28)
	at gov.nasa.jpf.jdart.config.ConcolicMethodConfig.read(ConcolicMethodConfig.java:30)
	at gov.nasa.jpf.jdart.config.ConcolicConfig.initialize(ConcolicConfig.java:217)
	at gov.nasa.jpf.jdart.config.ConcolicConfig.<init>(ConcolicConfig.java:76)
	at gov.nasa.jpf.jdart.JDart.<init>(JDart.java:72)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gov.nasa.jpf.Config.getInstance(Config.java:1985)
	... 3 more

**Comment by ksluckow** [comment]
Thank you for reporting this! The jpf config for the ctor was indeed incorrect. I have fixed it now.
